ALTER TYPE "TelegramSessionState" ADD VALUE IF NOT EXISTS 'CURATOR_ADD_NAME';
ALTER TYPE "TelegramSessionState" ADD VALUE IF NOT EXISTS 'CURATOR_ADD_EMAIL';
ALTER TYPE "TelegramSessionState" ADD VALUE IF NOT EXISTS 'CURATOR_ADD_PHONE';
ALTER TYPE "TelegramSessionState" ADD VALUE IF NOT EXISTS 'CURATOR_ADD_ANIMAL';
ALTER TYPE "TelegramSessionState" ADD VALUE IF NOT EXISTS 'CURATOR_ADD_AMOUNT';
ALTER TYPE "TelegramSessionState" ADD VALUE IF NOT EXISTS 'CAT_SEARCH';
